### ISSUE TITLE
Optimize assets in size using webp format 

### ISSUE THREAD

**Issue by graphene1over** [MiahaCybersec/netrunner.academy#53]
The images used in the website aren't necessarily large, but  their size could be further improved by converting them to webp.

**Comment by MiahaCybersec** [comment]
Thanks for the issue! I'll take a look later tonight to see if the images can be optimized any further. Moving the images into folders for each OS might help clean up the repository a bit as well.

**Comment by MiahaCybersec** [comment]
Some images became larger once converted to `webp`, but those that became smaller have been converted. Additionally, it looks like [Astro Starlight](https://starlight.astro.build/) does some image optimization during the build phase. Closing this issue since the latest commit has resolve it 👍
